'\" t
.\"
.pc
.TH AUALE 6 "2020-09-10" "2.0.0" "Aualé Manual"
.SH NAME
Aualé \- Play Oware Mancala against the computer
.\" ********************************************************************
.SH SYNOPSIS
.B auale
.RB [\| OPTIONS \|]
.RI [\| match_file \|]
.\" ********************************************************************
.SH DESCRIPTION
.B Oware
is a strategy board game of the Mancala family.
.PP
The goal of Oware is to capture the greatest amount of seeds as possible. To
do so, players make moves in alternate turns until one of them has captured
more than 24 seeds. The player who captured more seeds than the opponent when
the game ends wins the match.
.PP
Play against one of the strongest computer players out there, watch it play
alone while you learn or choose one of the provided strengths: easy, medium,
hard or expert.
.PP
Analyze, record, tag and share your own Mancala games. Aualé can save your
Oware matches in a portable and human-readable format.
.\" ********************************************************************
.SH OPTIONS
.TP
.RI \| match_file \|
Specifies a match file to open when.
.B Aualé
starts.
.TP
.BR \-\-debug
Enable the debug mode.
.TP
.BR \-\-engine=<command>
Set the engine to use.
.TP
.BR \-\-fullscreen
Start in fullscreen mode.
.TP
.BR \-\-help
Show a help message and exit.
.TP
.BR \-\-version
Show program's version number and exit.
.\" ********************************************************************
.SH AUTHORS
2014-2020 Joan Sala (contact@joansala.com)
